"use server";

// Manga CRUD Server Actions. Own-check semantics: uploaders can edit only
// manga they own (uploadedById); editors/super-admin can edit any. Publishing
// and deleting require the dedicated permission. Slugs are read-only after
// create (auto-generated by the Manga pre-validate hook).

import { Types } from "mongoose";

import "@/models";
import { connect } from "@/lib/db/mongoose";
import { Manga, type MangaDoc } from "@/models";
import { Chapter } from "@/models";
import { requireCan } from "@/lib/auth/assert";
import { asActionError, type ActionResult } from "@/lib/actions/_shared";
import { can, canEditManga, type Ownable } from "@/lib/auth/rbac";
import type { MangaStatus, MangaType } from "@/lib/constants";
import {
  revalidateManga,
  revalidateAdminManga,
  revalidateChapters,
} from "@/lib/utils/revalidate";
import { UPLOAD_ROOT } from "@/lib/utils/upload-path";
import { promises as fs } from "node:fs";
import path from "node:path";

export interface CreateMangaInput {
  title: string;
  altTitles?: string[];
  description?: string;
  author?: string;
  artist?: string;
  status?: MangaStatus;
  type?: MangaType;
  year?: number | null;
  coverImage?: string;
  bannerImage?: string;
  genreIds?: string[];
  tagIds?: string[];
  isPublished?: boolean;
  isHidden?: boolean;
}

export interface UpdateMangaInput extends Partial<CreateMangaInput> {
  uploadedById?: string;
}

function toObjectId(s: string): Types.ObjectId | null {
  return Types.ObjectId.isValid(s) ? new Types.ObjectId(s) : null;
}

async function loadManga(id: string) {
  const oid = toObjectId(id);
  if (!oid) return null;
  return (await Manga.findById(oid).lean()) as (MangaDoc & { _id: Types.ObjectId }) | null;
}

export async function createManga(
  input: CreateMangaInput,
): Promise<ActionResult<{ id: string; slug: string }>> {
  try {
    await connect();
    const user = await requireCan("manga:create");

    if (!input.title || !input.title.trim()) {
      return { ok: false, error: "Title is required" };
    }

    // Uploaders cannot publish. Drop the flag unless the user holds manga:publish.
    const canPublish = can(user.role, "manga:publish");
    const wantsPublished = Boolean(input.isPublished);

    const doc = await Manga.create({
      title: input.title.trim(),
      altTitles: (input.altTitles ?? []).filter((s) => s.trim()).map((s) => s.trim()),
      description: input.description ?? "",
      author: input.author ?? "",
      artist: input.artist ?? "",
      status: input.status ?? "ongoing",
      type: input.type ?? "manga",
      year: input.year ?? null,
      coverImage: input.coverImage ?? "",
      bannerImage: input.bannerImage ?? "",
      genres: (input.genreIds ?? []).map(toObjectId).filter(Boolean) as Types.ObjectId[],
      tags: (input.tagIds ?? []).map(toObjectId).filter(Boolean) as Types.ObjectId[],
      // Never trust client for these:
      views: 0,
      rating: 0,
      ratingCount: 0,
      uploadedById: new Types.ObjectId(user.id),
      isPublished: wantsPublished && canPublish,
      isHidden: Boolean(input.isHidden),
      publishedAt: wantsPublished && canPublish ? new Date() : null,
    });

    revalidateManga(doc.slug);
    revalidateAdminManga();
    return { ok: true, data: { id: doc.id, slug: doc.slug } };
  } catch (e) {
    return asActionError(e);
  }
}

export async function updateManga(
  id: string,
  input: UpdateMangaInput,
): Promise<ActionResult<{ id: string; slug: string }>> {
  try {
    await connect();
    const user = await requireCan("manga:create");

    const manga = await loadManga(id);
    if (!manga) return { ok: false, error: "Manga not found" };

    const fullUser: Ownable = { id: user.id, role: user.role };
    if (!canEditManga(fullUser, manga)) {
      return { ok: false, error: "You can only edit manga you own" };
    }

    const update: Record<string, unknown> = {};
    if (input.title !== undefined) {
      if (!input.title.trim()) return { ok: false, error: "Title cannot be empty" };
      update.title = input.title.trim();
    }
    if (input.altTitles !== undefined) {
      update.altTitles = input.altTitles.filter((s) => s.trim()).map((s) => s.trim());
    }
    if (input.description !== undefined) update.description = input.description;
    if (input.author !== undefined) update.author = input.author;
    if (input.artist !== undefined) update.artist = input.artist;
    if (input.status !== undefined) update.status = input.status;
    if (input.type !== undefined) update.type = input.type;
    if (input.year !== undefined) update.year = input.year;
    if (input.coverImage !== undefined) update.coverImage = input.coverImage;
    if (input.bannerImage !== undefined) update.bannerImage = input.bannerImage;
    if (input.genreIds !== undefined) {
      update.genres = input.genreIds.map(toObjectId).filter(Boolean) as Types.ObjectId[];
    }
    if (input.tagIds !== undefined) {
      update.tags = input.tagIds.map(toObjectId).filter(Boolean) as Types.ObjectId[];
    }
    if (input.isHidden !== undefined) update.isHidden = Boolean(input.isHidden);

    // isPublished requires manga:publish.
    if (input.isPublished !== undefined) {
      if (!can(user.role, "manga:publish")) {
        return { ok: false, error: "You cannot change the published state" };
      }
      const nextPublished = Boolean(input.isPublished);
      update.isPublished = nextPublished;
      if (nextPublished && !manga.publishedAt) update.publishedAt = new Date();
      if (!nextPublished) update.publishedAt = null;
    }

    // uploadedById reassign requires staff:manage (handled by reassignUploader).
    // We intentionally drop any client-supplied uploadedById here.

    const updated = await Manga.findByIdAndUpdate(manga._id, { $set: update }, { new: true })
      .lean() as (MangaDoc & { _id: Types.ObjectId }) | null;

    revalidateManga(updated?.slug);
    revalidateAdminManga();
    return { ok: true, data: { id: manga._id.toString(), slug: updated?.slug ?? "" } };
  } catch (e) {
    return asActionError(e);
  }
}

export async function deleteManga(id: string): Promise<ActionResult<{ id: string }>> {
  try {
    await connect();
    await requireCan("manga:delete");

    const oid = toObjectId(id);
    if (!oid) return { ok: false, error: "Invalid id" };

    const manga = (await Manga.findById(oid).lean()) as MangaDoc | null;
    if (!manga) return { ok: false, error: "Manga not found" };

    await Chapter.deleteMany({ mangaId: oid });
    await Manga.deleteOne({ _id: oid });

    // Best-effort cleanup of the manga's upload directory.
    try {
      const dir = path.resolve(UPLOAD_ROOT, "manga", id);
      await fs.rm(dir, { recursive: true, force: true });
    } catch {
      // swallowed — orphaned uploads are non-fatal
    }

    revalidateManga(manga.slug);
    revalidateAdminManga();
    return { ok: true, data: { id } };
  } catch (e) {
    return asActionError(e);
  }
}

export async function setMangaPublished(
  id: string,
  published: boolean,
): Promise<ActionResult<{ id: string }>> {
  try {
    await connect();
    await requireCan("manga:publish");

    const oid = toObjectId(id);
    if (!oid) return { ok: false, error: "Invalid id" };

    const manga = await Manga.findByIdAndUpdate(
      oid,
      {
        $set: {
          isPublished: published,
          publishedAt: published ? new Date() : null,
        },
      },
      { new: true },
    ).lean() as MangaDoc | null;

    if (!manga) return { ok: false, error: "Manga not found" };
    revalidateManga(manga.slug);
    revalidateAdminManga();
    return { ok: true, data: { id } };
  } catch (e) {
    return asActionError(e);
  }
}

export async function setMangaHidden(
  id: string,
  hidden: boolean,
): Promise<ActionResult<{ id: string }>> {
  try {
    await connect();
    await requireCan("manga:editAny");

    const oid = toObjectId(id);
    if (!oid) return { ok: false, error: "Invalid id" };

    const manga = await Manga.findByIdAndUpdate(
      oid,
      { $set: { isHidden: hidden } },
      { new: true },
    ).lean() as MangaDoc | null;

    if (!manga) return { ok: false, error: "Manga not found" };
    revalidateManga(manga.slug);
    revalidateAdminManga();
    return { ok: true, data: { id } };
  } catch (e) {
    return asActionError(e);
  }
}

export async function reassignUploader(
  id: string,
  uploaderId: string,
): Promise<ActionResult<{ id: string }>> {
  try {
    await connect();
    await requireCan("staff:manage");

    const oid = toObjectId(id);
    const uploaderOid = toObjectId(uploaderId);
    if (!oid || !uploaderOid) return { ok: false, error: "Invalid id" };

    const manga = await Manga.findByIdAndUpdate(
      oid,
      { $set: { uploadedById: uploaderOid } },
      { new: true },
    ).lean() as MangaDoc | null;

    if (!manga) return { ok: false, error: "Manga not found" };
    revalidateManga(manga.slug);
    revalidateAdminManga();
    revalidateChapters(id);
    return { ok: true, data: { id } };
  } catch (e) {
    return asActionError(e);
  }
}
